### ISSUE TITLE
tables2table.py doesn't work if not simply concatenating tables

### ISSUE THREAD

**Issue by nickilott** [cgat-developers/cgat-apps#129]
Hello!

It looks like the update from combine_tables.py i.e. tables2table.py doesn't work if it isn't a pure concatenation (unless I'm missing something). If args.cat = None then the table object isn't created i.e. at line 283:

``` 
if args.cat:
        table = concatenate_tables(args.filenames,
                                   regex_filename=args.regex_filename,
                                   separator=args.separator,
                                   headers=args.headers,
                                   missing_value=args.missing_value,
                                   cat=args.cat)

table.to_csv(args.stdout, sep=args.separator, index=False)
```

would removing the ```if args.cat:``` work as a fix as cat=args.cat is an argument ot the concatenate_tables functions?

Thanks!!

Nick

**Comment by Acribbs** [comment]
Yes I think you are correct, I made a pull request here #130. Might be worth testing it.

**Comment by Acribbs** [comment]
closing as pull request now merged, reopen if its not fixed.

**Comment by nickilott** [comment]
Thanks, will take a look!

**Comment by IanSudbery** [comment]
Hmm... No, this is wrong. 

Now instead of testing whether it should do a "concatenation" (`bind_rows` in tidyverse speak) or a join (`inner_join` in tidyverse speak), and doing nothing if its a join, if just goes ahead and tries to do a concatenation, whether that's what the users wants or not. 

Once upon a time (in a mixture of python and R style pseudocode), combine_tables used to do:

```python 
tables = lapply(read_delim, args.filenames)

table_names = extract(args.regex, args.filenames)
names(tables) = table_names

if args.cat:

    tables = lapply(tables, function(x) select(x, args.columns))
    result = bind_rows(tables, .id=args.cat)

else:
   tables = lapply(tables, function(x) select(x, c(args.columns, args.take))
   result = tables[[i]]
   for i in range(1, len(tables) - 1):
       colnames(table[[i]])[args.take] = table_names[i]
       result = inner_join(result, tables[[i]], on=args.columns)

```
Apart from it had all sorts of bells and whistles for manipulating column names/values, and the concatentate mode worked out of memory. 
It was useful for turning a collection of featureCounts files into an expression matrix, for example.
