### ISSUE TITLE
cythoning CGAT/BamTools/bamtools.pyx fails

### ISSUE THREAD

**Issue by AntonioJBT** [cgat-developers/cgat-apps#7]
Hello,
I'm doing a manual installation with
`python setup.py develop`

which fails when trying to compile with:
```
running develop
running egg_info
writing dependency_links to CGAT.egg-info/dependency_links.txt
writing entry points to CGAT.egg-info/entry_points.txt
writing CGAT.egg-info/PKG-INFO
writing requirements to CGAT.egg-info/requires.txt
writing top-level names to CGAT.egg-info/top_level.txt
reading manifest file 'CGAT.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CGAT/tools/cgat.py'
warning: no files found matching 'CGAT/tools/version.py'
writing manifest file 'CGAT.egg-info/SOURCES.txt'
running build_ext
skipping 'CGAT/Components/Components.cpp' Cython extension (up-to-date)
skipping 'CGAT/NCL/cnestedlist.c' Cython extension (up-to-date)
skipping 'CGAT/Timeseries/cmetrics.c' Cython extension (up-to-date)
skipping 'CGAT/GeneModelAnalysis.c' Cython extension (up-to-date)
cythoning CGAT/BamTools/bamtools.pyx to CGAT/BamTools/bamtools.c
warning: CGAT/BamTools/bamtools.pyx:812:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:813:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:814:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:815:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:816:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:817:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:818:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:819:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:820:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:821:31: local variable 'alignment_details_view' referenced before assignment
warning: CGAT/BamTools/bamtools.pyx:822:31: local variable 'alignment_details_view' referenced before assignment

Error compiling Cython file:
------------------------------------------------------------
...
    cdef int c_min_insert_size = min_insert_size
    cdef int start, end, xstart, xend
    cdef int take_columns = 6

    # point to array of contig lengths
    cdef uint32_t *contig_sizes = input_samfile.header.ptr.target_len
                                                     ^
------------------------------------------------------------

CGAT/BamTools/bamtools.pyx:1991:54: Object of type 'bam_hdr_t' has no attribute 'ptr'

Error compiling Cython file:
------------------------------------------------------------
...
    cdef int c_min_insert_size = min_insert_size
    cdef int start, end, xstart, xend
    cdef int take_columns = 6

    # point to array of contig lengths
    cdef uint32_t *contig_sizes = input_samfile.header.ptr.target_len
                                                         ^
------------------------------------------------------------

CGAT/BamTools/bamtools.pyx:1991:58: Cannot convert Python object to 'uint32_t *'
building 'CGAT.BamTools.bamtools' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/antoniob/anaconda/envs/cgat-core/include -arch x86_64 -I/Users/antoniob/anaconda/envs/cgat-core/lib/python3.5/site-packages/pysam -I/Users/antoniob/anaconda/envs/cgat-core/lib/python3.5/site-packages/pysam/include/htslib -I/Users/antoniob/anaconda/envs/cgat-core/lib/python3.5/site-packages/pysam/include/samtools -I/Users/antoniob/anaconda/envs/cgat-core/lib/python3.5/site-packages/numpy/core/include -I/Users/antoniob/anaconda/envs/cgat-core/include/python3.5m -c CGAT/BamTools/bamtools.c -o build/temp.macosx-10.9-x86_64-3.5/CGAT/BamTools/bamtools.o
CGAT/BamTools/bamtools.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: command 'gcc' failed with exit status 1
```

Best,
Antonio

**Comment by sebastian-luna-valero** [comment]
Thanks, Antonio.

Could you please follow the automatic installation steps instead and let me know how it goes?
https://github.com/cgat-developers/cgat-apps/blob/master/README.rst

Best regards,
Sebastian

**Comment by AntonioJBT** [comment]
Thanks, I tried this but got an error, I've sent the log separately. Part of it was:
```
An error occurred in:

 - line number: 252
 - exit status: 1
 - command: conda env create --quiet --name ${CONDA_INSTALL_ENV} --file env-apps.yml
```

It's more convenient at the moment to install manually though as I already have several conda environments where I'm running other code that would rely on CGAT tools. 
What would the best way to manage this be?
Although the install script is very convenient I'm not sure I want multiple conda installs, or replace the current setup I have.
Any suggestions let me know...!
Antonio

**Comment by sebastian-luna-valero** [comment]
Hi Antonio,

The install script aims to be idempotent and self-contained. It does not require an existing conda installation to work and it should not affect existing ones either.

We are moving from manual to automated installation to have a predictable way of getting the code to work. I am sorry, I won't be able to support manual installations since everyone's environment is very likely to be unique.

If you want to go ahead with the automated installation, please try these steps:
```
curl -O https://raw.githubusercontent.com/cgat-developers/cgat-apps/SLV-install/install-CGAT-tools.sh
bash install-CGAT-tools.sh --production --location ~/Documents/github.dir/bin/cgat_installation
```

and let me know how it goes.

Best regards,
Sebastian

**Comment by AntonioJBT** [comment]
Hi Sebastian,
This installed without errors and on a quick check works. I agree with having the install script of course, it greatly facilitates things. I had assumed the cython error might be a more general problem. I'll close this now.
Thanks!
Antonio

**Comment by sebastian-luna-valero** [comment]
Many thanks for your feedback!

FYI, since we have not released `cgat-apps` yet, right now `--devel` and `--production` will install the same collection of CGAT scripts from github but different conda environments. This is a workaround until a first release of `cgat-apps` is published. Only the [subset of production](https://github.com/cgat-developers/cgat-apps/blob/master/MANIFEST.in) scripts are guaranteed to work with the `--production` option.

The `--devel` option installs all the dependencies, and the error you had earlier is related to the [util-linux](https://anaconda.org/anaconda/util-linux) package being available only for Linux and not OS X. This is required by the `rename` command in the [Sra.py](https://github.com/cgat-developers/cgat-apps/blob/master/CGAT/Sra.py#L184) module file.

It should be possible to replace `rename` but it needs some thought to get rid of the `util-linux` dependency, allowing then the `--devel` option to work in OS X as well.

Best regards,
Sebastian

**Comment by AntonioJBT** [comment]
Ah, good to know. Thanks @sebastian-luna-valero !
